[project]
name = "web-practice-2026"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lilnoahhh", email = "redhouse0715@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "python-dotenv>=1.0.0",
    "sqlalchemy>=2.0",
    "alembic>=1.13",
    "psycopg[binary]>=3.2",
]

[project.scripts]
web-practice-2026 = "web_practice_2026:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[tool.fastapi]
entrypoint = "main:app"
