"""add salary range to application

Revision ID: 1f8bc05f0042
Revises: 1168ae495714
Create Date: 2026-09-27 15:49:51.096931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f8bc05f0042'
down_revision: Union[str, Sequence[str], None] = '1168ae495714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('practice_applications')
    op.add_column('application', sa.Column('salary_min', sa.Integer(), nullable=True))
    op.add_column('application', sa.Column('salary_max', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'salary_max')
    op.drop_column('application', 'salary_min')
    op.create_table('practice_applications',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('company', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('practice_applications_pkey'))
    )
    # ### end Alembic commands ###
